config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :tasks, only: [:index, :update, :destroy]
  end
  
  namespace :admin do
    root 'tasks#index'
    resources :users, only: [:index, :show]
    resources :tasks
    resources :registrations
    resources :labels, only: [:index, :new, :create, :destroy]
    resources :groups do
      resources :users do
        resource :group_users, only: :destroy
      end
    end
  end

  resources :tasks do
    get :calendar, on: :collection
  end
  resources :sessions, only: [:new, :create]
  resources :labels, only: [:index]
  resources :users, only: [:show, :update, :edit]
  resources :groups do
    resources :users do
      resource :group_users, only: :destroy
    end
  end
  delete "/session" => "sessions#destroy", as: :destroy_session
  root "tasks#index"
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :delete_all
  has_many :users, through: :group_users
  has_many :tasks

  accepts_nested_attributes_for :group_users,  allow_destroy: true
  
  validates :name, presence: true
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_group, only: [:show, :destroy, :edit, :update]

  layout 'admin'

  def index
    @groups = Group.all.includes(:group_users)
  end

  def show
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "作成しました"
      head :ok
    else
      render json: { messages: @group.errors.full_messages }, status: :bad_request
    end
  end

  def edit
    @group.users.build
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "更新しました"
      head :ok
    else
      render json: { messages: @group.errors.full_messages }, status: :bad_request
    end
  end

  def destroy
    if @group.destroy
      flash[:notice] = "削除しました"
      redirect_to groups_path
    else
      flash[:danger] = "削除できませんでした"
      redirect_to group_path(@group)
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :description, group_users_attributes: [:user_id, :group_id, :_destroy, :id])
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :destroy, :edit, :update]
  
  def index
    @groups = @current_user.groups
  end
  
  def show
    authenticate_group_member!
  end
  
  def new
    @group = Group.new
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "作成しました"
      head :ok
    else
      render json: { messages: @group.errors.full_messages }, status: :bad_request
    end
  end
  
  def edit
    @group.users.build
  end
  
  def update
    if @group.update(group_params)
      flash[:notice] = "更新しました"
      head :ok
    else
      render json: { messages: @group.errors.full_messages }, status: :bad_request
    end
  end
  
  def destroy
    if @group.destroy
      flash[:notice] = "削除しました"
      redirect_to groups_path
    else
      flash[:danger] = "削除できませんでした"
      redirect_to group_path(@group)
    end
  end
  
  private
    def group_params
      params.require(:group).permit(:name, :description, group_users_attributes: [:user_id, :group_id, :_destroy, :id])
    end
    
    def set_group
      @group = Group.find(params[:id])
    end
  
    def authenticate_group_member!
      unless @current_user.group_ids.include?(@group.id)
        flash[:danger] = "このプロジェクトに参加しておりません"
        redirect_to :back
      end
    end
end

app/views/groups/_form.html.slim
.container-fluid
  .row
    .col-sm-12
      .panel.panel-default.mt20
        .panel-body
          = form_for @group, html: { id: "data-form" } do |f|
            .col-sm-12
              .form-group
                = f.label :name, "グループ名"
                = f.text_field :name, class: "form-control"
            .col-sm-12
              .form-group
                = f.label :description, "説明"
                = f.text_field :description, class: "form-control"
            .col-sm-2
              .form-group
                = select_tag 'group_users', options_for_select(User.all.map { |user| [user.username, user.id] }), include_blank: true, multiple: true, id: "user-select"
            .col-sm-12.mt20
              .form-group
                = link_to "戻る", :back, class: "default-btn"
                .btn.main-btn.pull-right.data-submit 作成

app/views/groups/edit.html.slim
.container-fluid
  .row
    .col-sm-12
      .panel.panel-default.mt20
        .panel-body
          = form_for @group, html: { id: "data-form" } do |f|
            .col-sm-12
              label 追加
              .form-group
                = select_tag 'group_users', options_for_select(User.where.not(id: @group.user_ids).map { |user| [user.username, user.id] }), include_blank: true, multiple: true, id: "user-select"
            .col-sm-12.mt20
              .form-group
                = link_to "戻る", :back, class: "default-btn"
                .btn.main-btn.pull-right.data-submit 追加

app/views/groups/index.html.slim
.container-fluid.mt20
  .row
    .col-sm-12
      = link_to new_group_path, class: "main-btn" do
        i.fas.fa-plus  プロジェクト
  .row
    .col-sm-12
      .panel.panel-default.mt20
        .panel-body
          table.table
            thead
              tr
                th = Group.human_attribute_name(:name)
                th 所属人数
                th タスク数
                th 作成日
                th
            tbody.data-tbody.sortable
              - @groups.each do |group|
                tr
                  td = link_to group.name, group_path(group.id)
                  td = group.users.size
                  td = group.tasks.exclude_complete.size
                  td = l group.created_at

app/views/groups/new.html.slim
= render 'form'

app/views/groups/show.html.slim
.container-fluid#group-show
  .row
    .col-sm-12.clearfix.mt10
      h4.page-title.pull-left
        = @group.name

  .row
    .col-sm-12.mt20
      - @group.users.each do |user|
        label.groups-user-img
          = link_to group_user_group_users_path(@group, user), data: { confirm: "プロジェクトからこのユーザーを削除します。よろしいですか？" }, method: :delete do
            = attachment_image_tag user, :image, :fill, 80, 80, class: "img-circle mr10 "
            span.user-info
              = user.username
  .row
    .col-sm-12
       .panel.panel-default.mt20
         .panel-body
           .col-sm-10
             p style="color: #888888; font-size: 12px;"
               = @group.description
           .col-sm-2
             .btn-group.pull-right.mt0
               a.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                 i.fas.fa-bars
               .dropdown-menu
                 li
                   = link_to "タスク作成", new_task_path(id: @group.id), class: "dropdown-item"
                 li
                   = link_to "ユーザーを追加", edit_group_path(@group), class: "dropdown-item"
                 li
                   = link_to "プロジェクトを削除", group_path, method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: "dropdown-item"
           table.mt30.table
             thead
               tr
                 th
                 th = Task.human_attribute_name(:title)
                 th = Task.human_attribute_name(:deadline_on)
                 th = Task.human_attribute_name(:priority)
                 th = Task.human_attribute_name(:status)
                 th = Task.human_attribute_name(:created_at)
                 th = Task.human_attribute_name(:responsible)
                 th = Task.human_attribute_name(:user)
                 th ラベル
                 th
             tbody.data-tbody.sortable
               - @group.tasks.exclude_complete.each do |task|
                 tr
                   td
                     input type="checkbox" name="task_id" value="#{task.id}"
                   td.td-title = task.title
                   td.td-deadlineon
                     = l task.deadline_on
                   td.td-priority
                     label class="label label-#{task.priority_color_class}" = task.human_priority
                   td.td-status
                     label class="label label-#{task.status_color_class}" = task.human_status
                   td.td-createdat = l task.created_at
                   td = task.responsible.username.truncate(8)
                   td = task.user.username.truncate(8)
                   td
                     - task.labels.each.with_index(1) do |label, i|
                       = link_to tasks_path(task: { 'label_ids' => [label.id] }) do
                         label.selected-label-green = label.name
                       - if  i % 2 == 0
                         br
                   td
                     = link_to edit_task_path(task) do
                       .btn.btn-default.edit-task-btn
                         i.fas.fa-pencil-alt
         .panel-footer.clearfix
           .btn.default-btn.pull-right.ml10.collect-update 一括完了