config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :tasks, only: [:index, :update, :destroy]
  end
  
  namespace :admin do
    root 'tasks#index'
    resources :users, only: [:index, :show]
    resources :tasks
    resources :registrations
    resources :labels, only: [:index, :new, :create, :destroy]
    resources :groups do
      resources :users do
        resource :group_users, only: :destroy
      end
    end
  end

  resources :tasks do
    get :calendar, on: :collection
  end
  resources :sessions, only: [:new, :create]
  resources :labels, only: [:index]
  resources :users, only: [:show, :update, :edit]
  resources :groups do
    resources :users do
      resource :group_users, only: :destroy
    end
  end
  delete "/session" => "sessions#destroy", as: :destroy_session
  root "tasks#index"
end

app/views/shared/_admin_header.html.slim
header#header.clearfix
  h1.header-icon
    = link_to "Task M", admin_root_path
  div.admin-header-nav
    - if @current_user.present?
      span.account-icon.pull-right
        .dropdown
          a.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            = attachment_image_tag @current_user, :image, :fill, 50, 50, class: "img-circle"
            span.caret
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            li.dropdown-header = @current_user.username
            li
              = link_to "マイページ", admin_user_path(@current_user)
            li
              = link_to "ログアウト", destroy_session_path, method: :delete

app/views/shared/_admin_sidebar.html.slim
div#admin-sidemenu.pt60
  nav
    ul
      = link_to admin_tasks_path do
        li
          i.fas.fa-tasks 　タスク管理
      = link_to admin_groups_path do
        li
          i.fas.fa-user-friends 　プロジェクト
      = link_to admin_labels_path do
        li
          i.fas.fa-tags 　ラベルマスタ
      = link_to admin_users_path do
        li
          i.fas.fa-users 　ユーザ一覧
      = link_to new_admin_registration_path do
        li
          i.fas.fa-user-plus 　アカウント追加
      = link_to root_path do
        li
          i.fas.fa-male 　一般ページ

app/views/shared/_flash.html.slim
- if flash.present?
  - flash.each do |key, value|
    - status = "success" if key == "notice"
    - status = "error"  if key == "danger"
    javascript:
      $(function(){
        toastr.#{status}("#{value}");
      })

- if flash[:close_deadline].present?
  javascript:
      $(function () {
          toastr.error("#{flash[:close_deadline]}");
      })

- if flash[:too_deadline].present?
  javascript:
      $(function () {
          toastr.error("#{flash[:too_deadline]}");
      })

- if @errors.present?
  - @errors.each do |error|
    javascript:
          $(function(){
            toastr.error("#{error}");
          })

app/views/shared/_footer.html.slim
footer 
  = render "shared/flash"
  
script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"
script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"
script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"
script src='https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js'
script src="https://www.gstatic.com/charts/loader.js"
script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.28/vue.min.js'
script src='https://unpkg.com/axios/dist/axios.min.js'

app/views/shared/_head.html.slim
head
  title Ashita Task Management

  = csrf_meta_tags
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = favicon_link_tag("/assets/images/favicon.ico")
  link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
  link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous"
  link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/css/datepicker.css" rel="stylesheet" type="text/css"
  link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css'

app/views/shared/_header.html.slim
header#header.clearfix
  h1.header-icon
    = link_to "Task M", root_path
  div.header-nav
    - if @current_user.present?
      span.account-icon.pull-right
        .dropdown
          a.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            = attachment_image_tag @current_user, :image, :fill, 50, 50, class: "img-circle"
            span.caret
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            li.dropdown-header = @current_user.username
            li
              = link_to "マイページ", user_path(@current_user)
            li
              = link_to "ログアウト", destroy_session_path, method: :delete

app/views/shared/_sidebar.html.slim
div#sidemenu.pt60
  nav
    ul
      = link_to root_path do
        li
          i.fas.fa-tasks　すべてのタスク
      = link_to groups_path do
        li
          i.fas.fa-user-friends　プロジェクト
      = link_to calendar_tasks_path do
        li
          i.far.fa-calendar-alt　 カレンダー
      - if @current_user.role == "admin"
        = link_to admin_root_path do
          li
            i.fas.fa-unlock-alt 　 管理者専用