config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :tasks, only: [:index, :update, :destroy]
  end
  
  namespace :admin do
    root 'tasks#index'
    resources :users, only: [:index, :show]
    resources :tasks
    resources :registrations
    resources :labels, only: [:index, :new, :create, :destroy]
    resources :groups do
      resources :users do
        resource :group_users, only: :destroy
      end
    end
  end

  resources :tasks do
    get :calendar, on: :collection
  end
  resources :sessions, only: [:new, :create]
  resources :labels, only: [:index]
  resources :users, only: [:show, :update, :edit]
  resources :groups do
    resources :users do
      resource :group_users, only: :destroy
    end
  end
  delete "/session" => "sessions#destroy", as: :destroy_session
  root "tasks#index"
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :tasks, :class_name => 'Task', :foreign_key => 'user_id'
  has_many :responsibles, :class_name => 'Task', :foreign_key => 'responsible_id'
 
  has_secure_password validations: true
  
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true
  
  before_create :set_default_role
  before_destroy :validates_must_exist_admin, if: :one_person_following?
  before_destroy :validates_has_tasks
  
  ROLE = { normal: 0, admin: 1 }
  enum role: ROLE
  
  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
  
  def self.search(params)
    users = User.all
    return users if params.blank?
    
    if params[:username].present?
      users = users.where("username like ?", "%#{params[:username]}%")
    end
    users
  end

  def human_roles
    I18n.t "enum.users.roles.#{self.role}"
  end

  def self.role_options
    I18n.t 'enum.users.roles'
  end
  
  def completed_tasks
    self.responsibles.where(status: "complete")
  end
  
  def admin?
    self.role == "admin" ? true : false
  end
  
  private
    def set_default_role
      self.role ||= 0
    end
  
    def validates_must_exist_admin
      errors.add :base, "少なくとも管理者が１人必要です"
      throw :abort
    end
  
    def one_person_following?
      User.where(role: "admin").length <= 1 && self.role == "admin"
    end
  
    def validates_has_tasks
      if self.tasks.present? || self.responsibles.present?
        errors.add :base, "紐付いたタスクがあります"
        throw :abort
      end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: :show
  layout 'admin'
  
  def index
    @users = User
      .search(params[:user])
    @q = params[:user].present? ? User.new(search_user_params) : User.new
  end
  
  def show
  end
  
  private
    def search_user_params
      params.require(:user).permit(:username, :created_at)
    end
  
    def set_user
      @user = User.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
	before_action :authenticate_user!

	def show
	end

	def edit
	end
  
  def update
		if @user.update(user_params)
			flash[:notice] = "更新しました"
			redirect_to user_path(@user)
		else
			flash[:danger] = "更新できませんでした"
			redirect_to user_path(@user)
		end
	end
  
  private
    def user_params
			params.require(:user).permit(:image, :email, :username, :password, :password_confirmation)
		end
  
    def set_user
			@user = User.find(params[:id])
		end
end

app/views/admin/users/index.html.slim
.container-fluid.mt40
  .row
    .col-sm-12
      .panel.panel-default
        .panel-body
          .row
            = form_for([:admin, @q], url: admin_users_path, method: :get) do |f|
              .col-sm-3
                = f.text_field :username, class: "form-control", placeholder: "ユーザー名"
              .col-sm-1
                = button_tag id: "search-button", class: "main-btn-block" do
                  i.glyphicon.glyphicon-search
              .col-sm-1
                = link_to admin_users_path, id: "reset-button", class: "sub-btn-block" do
                  i.fas.fa-times
          hr
          .col-sm-12
            table.table
              thead
                tr
                  th = User.human_attribute_name(:username)
                  th = User.human_attribute_name(:email)
                  th タスク数
                  th = User.human_attribute_name(:created_at)
                  th = User.human_attribute_name(:role)
                  th
              tbody
                - @users.each do |user|
                  tr
                    td = user.username
                    td = user.email
                    td
                      = user.responsibles.exclude_complete.size
                      | 個
                    td = l user.created_at
                    td = user.human_roles
                    td = link_to "詳細を見る", admin_user_path(user), class: "main-btn"

app/views/admin/users/show.html.slim
.container-fluid.mt40
  .row
    .col-sm-12
      .panel.panel-default
        .panel-body
          .col-sm-4.text-center
            .col-sm-12
              = attachment_image_tag @user, :image, :fill, 200, 200, class: "img-responsibe img-circle"
            .col-sm-6.mt30
              = link_to edit_admin_registration_path(@user), class: "main-btn-block" do
                i.fas.fa-pencil-alt
            .col-sm-6.mt30
              = link_to admin_registration_path(@user), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-block" do
                i.fas.fa-trash-alt

          .col-sm-8
            h3 = @user.username
            lable = @user.human_roles
            br
            table.table
              tbody
                tr
                  td id
                  td = @user.id
                tr
                  td = User.human_attribute_name(:email)
                  td = @user.email
                tr
                  td = User.human_attribute_name(:created_at)
                  td = l @user.created_at
                tr
                  td 作成したタスク
                  td = @user.tasks.size
                tr
                  td 担当しているタスク
                  td = @user.responsibles.exclude_complete.size
                tr
                  td 完了したタスク
                  td = @user.completed_tasks.size
                tr
                  td 所属しているプロジェクト
                  td
                    - @user.groups.each do |group|
                      = group.name
                      br